#!/bin/bash

# THIS SCRIPT MUST BE RUN AS ROOT

# Création des fichiers de configuration

cancelInstall() {
    echo "Installation annulée."
    # Undo all changes mades to system
    exit 1
}


while nfs_ip == ""; do
    echo "Veuillez entrer l'addresse ip de votre serveur NFS :"
    read nfs_ip
    if [ -z "$nfs_ip" ]; then
        echo "L'adresse IP ne peut pas être vide. Veuillez réessayer."
    fi
done

sleep 1

while smb_ip == ""; do
    echo "Veuillez entrer l'addresse ip de votre Serveur de stockage SMB :"
    read smb_ip
    if [ -z "$smb_ip" ]; then
        echo "L'adresse IP ne peut pas être vide. Veuillez réessayer."
    fi
done

sleep 1

while smb_share == ""; do
    echo "Veuillez entrer le nom de votre partage SMB :"
    read smb_share
    if [ -z "$smb_share" ]; then
        echo "Le nom du partage SMB ne peut pas être vide. Veuillez réessayer."
    fi
done

sleep 1

while pxeConfigDir == ""; do
    echo "Veuillez entrer le chemin de votre dossier de configuration du menu PXE (/tftpboot/pxelinux.cfg) :"
    read pxeConfigDir
    if [ -z "$pxeConfigDir" ]; then
        echo "Le chemin du dossier de configuration PXE ne peut pas être vide. Veuillez réessayer."
    fi
done

mkdir -p "/etc/czillapxe"
touch "/etc/czillapxe/czillapxe.cfg"

cat << EOF > /etc/czillapxe/czillapxe.cfg
# This file is used by CzillaPXE to configure the PXE menu and other settings
# Do not edit this file if you are not sure what you are doing.
# Check documentation for more informations

czillaNfsIp="$nfs_ip"
czillaSmbIp="$smb_ip"
czillaSmbShare="$smb_share"

pxeConfigDir="$pxeConfigDir"
czillaConfigFile="/etc/czillapxe/czillapxe.cfg"
czillaImageDir="/srv/partage/clonezilla"
czillaPxeMenu="$pxeConfigDir/clonezilla"
czillaScriptDir="/opt/czillapxe/scripts"
czillaBackupDir="/opt/czillapxe/backup"
czillaConfigDir="/etc/czillapxe"
czillaMainDir="/opt/czillapxe/main"
czillaTmpDir="/opt/czillapxe/tmp/clonezilla"
czillaLogDir="/var/log/czillapxe"

czillaServiceLog="/var/log/czillapxe/czillapxe_service.log"
czillaLogFile="/var/log/czillapxe/czillapxe.log"
czillaTmpMenu="/opt/czillapxe/tmp/clonezilla.tmp"
entriesFile="/opt/czillapxe/tmp/clonezilla_entries.tmp"
EOF

cat << EOF > /etc/czillapxe/.smbcredentials
username=clonezilla
password=clonezilla
EOF

source /etc/czillapxe/czillapxe.cfg
echo "Initialisation de CZillaPXE..."


# Création du répertoire Czilla

mkdir -p "$czillaScriptDir"
mkdir -p "$czillaMainDir"
mkdir -p "$czillaTmpDir"
mkdir -p "$czillaBackupDir"
mkdir -p "$(dirname "$czillaServiceLog")"
mv clonezilla "$pxeConfigDir/clonezilla"
touch $czillaConfigDir/.credentials


# Création des scripts
echo "Création des scripts..."

mv ./scripts/czillapxe.sh /usr/local/bin/czillapxe
mv ./scripts/czillapxe_autoconfig.sh /opt/czillapxe/scripts/czillapxe_autoconfig
mv ./scripts/czillapxe_service.sh /opt/czillapxe/scripts/czillapxe_service
mv ./scripts/czillapxe_tools.sh /opt/czillapxe/scripts/czillapxe_tools
mv ./scripts/czillapxe_add.sh /opt/czillapxe/scripts/czillapxe_add
mv ./scripts/logger.sh /opt/czillapxe/scripts/logger


echo "Création du point de montage czillapxe"
if [ ! -d "/srv/partage/clonezilla" ]; then
    mkdir -p /srv/partage/clonezilla
fi
mount -t cifs -o username=clonezilla,password=clonezilla //$smb_ip/$smb_share /srv/partage/clonezilla
if [ $? -ne 0 ]; then
    echo "Erreur lors du montage du partage SMB. Veuillez vérifier les informations de connexion."

    cancelInstall
    exit 1
fi

# Modification du fichier fstab pour ajouter montage automatique

echo "//$smb_ip/$smb_share /srv/partage/clonezilla cifs credentials=$czillaConfigDir/.smbcredentials,uid=1000,gid=1000,iocharset=utf8 0 0" >> /etc/fstab

# Modification du fichier ~/.bashrc pour ajouter l'autocomplétion

echo " " >> ~/.bashrc
echo " " >> ~/.bashrc
echo "# Autocomplétion pour czillapxe.sh" >> ~/.bashrc
echo " " >> ~/.bashrc
echo "_czilla_completions() {" >> ~/.bashrc
echo "    local cur prev opts" >> ~/.bashrc
echo "    COMPREPLY=()" >> ~/.bashrc
echo '    cur="${COMP_WORDS[COMP_CWORD]}"' >> ~/.bashrc
echo '    prev="${COMP_WORDS[COMP_CWORD-1]}"' >> ~/.bashrc
echo '    opts="add autoconfig help version"' >> ~/.bashrc
echo " " >> ~/.bashrc
echo '    if [[ ${cur} == -* ]]; then' >> ~/.bashrc
echo '        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )' >> ~/.bashrc
echo "    else" >> ~/.bashrc
echo '        case "${prev}" in' >> ~/.bashrc
echo "            add)" >> ~/.bashrc
echo '                COMPREPLY=( $(compgen -W "--image --name" -- ${cur}) )' >> ~/.bashrc
echo "                ;;" >> ~/.bashrc
echo "            autoconfig|help|version)" >> ~/.bashrc
echo "                COMPREPLY=()" >> ~/.bashrc
echo "                ;;" >> ~/.bashrc
echo "            *)" >> ~/.bashrc
echo '                COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )' >> ~/.bashrc
echo "                ;;" >> ~/.bashrc
echo "        esac" >> ~/.bashrc
echo "    fi" >> ~/.bashrc
echo "    return 0" >> ~/.bashrc
echo "}" >> ~/.bashrc
echo " " >> ~/.bashrc
echo "complete -F _czilla_completions czillapxe" >> ~/.bashrc

# Création du service systemd


echo "Création du service systemd pour CzillaPXE..."
echo "INFO : Pour des raison de sécurités et de portabilités, il est necessaire de réaliser un montage du dossier /srv/partage/clonezilla pour que le service czilla.service puisse s'executer"

touch /etc/systemd/system/czillapxe.service

if [ $? -ne 0 ]; then
    echo "Erreur lors de la création du fichier de service systemd."
    exit 1
fi

cat << EOF > /etc/systemd/system/czillapxe.service
[Unit]
Description=CzillaPXE Service
After=local-fs.target

[Service]
Type=simple
ExecStart=/opt/czillapxe/scripts/czillapxe_service
User=root
WorkingDirectory=$czillaMainDir
StandardOutput=append:$czillaServiceLog
StandardError=append:$czillaServiceLog
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable czillapxe.service
systemctl start czillapxe.service