#!/bin/bash

# THIS SCRIPT MUST BE RUN AS ROOT

# Création des fichiers de configuration

mkdir -p "/etc/czillapxe"
touch "/etc/czillapxe/czillapxe.cfg"

cat << EOF > /etc/czillapxe/czillapxe.cfg
# This file is used by CzillaPXE to configure the PXE menu and other settings
# Do not edit this file if you are not sure what you are doing.
# Check documentation for more informations

pxeConfigDir="/tftpboot/pxelinux.cfg"
czillaConfigFile="/etc/czillapxe/czillapxe.cfg"
czillaImageDir="/srv/partage/clonezilla"
czillaPxeMenu="/tftpboot/pxelinux.cfg/clonezilla"
czillaScriptDir="/opt/czillapxe/scripts"
czillaBackupDir="/opt/czillapxe/backup"
czillaConfigDir="/etc/czillapxe"
czillaMainDir="/opt/czillapxe/main"
czillaTmpDir="/opt/czillapxe/tmp/clonezilla"
czillaLogDir="/var/log/czillapxe"

czillaServiceLog="/var/log/czillapxe/czillapxe_service.log"
czillaLogFile="/var/log/czillapxe/czillapxe.log"
czillaTmpMenu="/opt/czillapxe/tmp/clonezilla.tmp"
entriesFile="/opt/czillapxe/tmp/clonezilla_entries.tmp"
EOF

source /etc/czillapxe/czillapxe.cfg
echo "Initialisation de CZillaPXE..."


# Création du répertoir Czilla

mkdir -p "$czillaScriptDir"
mkdir -p "$czillaMainDir"
mkdir -p "$czillaTmpDir"
mkdir -p "$czillaBackupDir"
mkdir -p "$(dirname "$czillaServiceLog")"
mv clonezilla "$pxeConfigDir/clonezilla"

# Création des scripts
echo "Création des scripts..."

mv ./scripts/czillapxe.sh /usr/local/bin/czillapxe
mv ./scripts/autoconfig.sh /opt/czillapxe/scripts/autoconfig
mv ./scripts/czillapxe_service.sh /opt/czillapxe/scripts/czillapxe_service
mv ./scripts/czillapxe_tools.sh /opt/czillapxe/scripts/czillapxe_tools
mv ./scripts/czilla_add.sh /opt/czillapxe/scripts/czilla_add
mv ./scripts/logger.sh /opt/czillapxe/scripts/logger

# Modification du fichier ~/.bashrc pour ajouter l'autocomplétion

echo " " >> ~/.bashrc
echo " " >> ~/.bashrc
echo "# Autocomplétion pour czillapxe.sh" >> ~/.bashrc
echo " " >> ~/.bashrc
echo "_czilla_completions() {" >> ~/.bashrc
echo "    local cur prev opts" >> ~/.bashrc
echo "    COMPREPLY=()" >> ~/.bashrc
echo '    cur="${COMP_WORDS[COMP_CWORD]}"' >> ~/.bashrc
echo '    prev="${COMP_WORDS[COMP_CWORD-1]}"' >> ~/.bashrc
echo '    opts="add autoconfig help version"' >> ~/.bashrc
echo " " >> ~/.bashrc
echo '    if [[ ${cur} == -* ]]; then' >> ~/.bashrc
echo '        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )' >> ~/.bashrc
echo "    else" >> ~/.bashrc
echo '        case "${prev}" in' >> ~/.bashrc
echo "            add)" >> ~/.bashrc
echo '                COMPREPLY=( $(compgen -W "--image --name" -- ${cur}) )' >> ~/.bashrc
echo "                ;;" >> ~/.bashrc
echo "            autoconfig|help|version)" >> ~/.bashrc
echo "                COMPREPLY=()" >> ~/.bashrc
echo "                ;;" >> ~/.bashrc
echo "            *)" >> ~/.bashrc
echo '                COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )' >> ~/.bashrc
echo "                ;;" >> ~/.bashrc
echo "        esac" >> ~/.bashrc
echo "    fi" >> ~/.bashrc
echo "    return 0" >> ~/.bashrc
echo "}" >> ~/.bashrc
echo " " >> ~/.bashrc
echo "complete -F _czilla_completions czillapxe" >> ~/.bashrc

# Création du service systemd


echo "Création du service systemd pour CZillaPXE..."
echo "INFO : Pour des raison de sécurités et de portabilités, il est necessaire de réaliser un montage du dossier /srv/partage/clonezilla pour que le service czilla.service puisse s'executer"

touch /etc/systemd/system/czillapxe.service

if [ $? -ne 0 ]; then
    echo "Erreur lors de la création du fichier de service systemd."
    exit 1
fi

cat << EOF > /etc/systemd/system/czillapxe.service
[Unit]
Description=CzillaPXE Service
After=local-fs.target

[Service]
Type=simple
ExecStart=/opt/czillapxe/scripts/czillapxe_service
User=root
WorkingDirectory=$czillaMainDir
StandardOutput=append:$czillaServiceLog
StandardError=append:$czillaServiceLog
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable czillapxe.service
systemctl start czillapxe.service